networks:
  shared_network:
    driver: bridge

services:
  devcontainer:

    env_file: .env

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    networks:
      - shared_network

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces/financial_db:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    image: postgres:15
    container_name: financial_data_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - shared_network
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DATA_DIR}/db:/var/lib/postgresql/data
